Update hooks to reflect vmkite changes

diff --git a/scripts/macos/hooks/environment b/scripts/macos/hooks/environment
--- a/scripts/macos/hooks/environment
+++ b/scripts/macos/hooks/environment
@@ -6,5 +6,21 @@ export HOMEBREW_NO_AUTO_UPDATE=1
 
 eval "$(rbenv init -)"
 
-echo "~~~ VMKite Stack Information"
+echo "~~~ :llama: VMKite Stack Information"
 cat /etc/vmkite-info
+
+echo VMKITE_API_HOST "${VMKITE_API_HOST:-}"
+echo VMKITE_API_HOST "${VMKITE_API_TOKEN:-}"
+
+if [[ -z $VMKITE_API_HOST ]] ; then
+  echo "+++ Missing VMKITE_API_HOST env"
+  exit 1
+fi
+
+if [[ -z $VMKITE_API_TOKEN ]] ; then
+  echo "+++ Missing VMKITE_API_TOKEN env"
+  exit 1
+fi
+
+curl -X POST "${VMKITE_API_HOST}/notify/hook/environment" \
+  -H "Authorization: Bearer ${VMKITE_API_TOKEN}"
